name: task5_face_app
description: "Morphy Face App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Features
  camera: ^0.10.5
  provider: ^6.1.1
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  
  # Saving & Sharing
  gal: ^2.3.0
  path_provider: ^2.1.2
  share_plus: ^7.2.0
  url_launcher: ^6.2.5

  # Photo Editing (Brightness/Contrast/Stickers)
  image_editor_plus: ^1.0.0
  http: ^1.2.0
  
  # Web Audio Support
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true